### ISSUE TITLE
exporting classe with privat constructors.

### ISSUE THREAD

**Issue by DerThorsten** [wjakob/pybind11#114]
Hi, Its me again, annoying user =)

The last thing which is missing for me in pybind11 is an equivalent
to boosts `no_init` in the case the constructor is privat.

So far I could not find anythning.
Any help =)?

Greetings

**Comment by wjakob** [comment]
Just don't define a constructor and see what happens :)

**Comment by DerThorsten** [comment]
well....It does not compile in that case...

**Comment by wjakob** [comment]
If something doesn't compile that would be quite surprising and indicate an issue -- please post a self-contained example in this case?

**Comment by DerThorsten** [comment]
Maybe it is a combination with the trampoline class and box2d's way of having constructors and destructors as protected members...
But so far I cannot compile things with pybind11 if I do not change these things from protected to
public.
If you are saying that this is a me-problem and pybind11 should handle that fine, I'll try to figure out whats going on (and in that case i am sry for stealing time :) )

**Comment by DerThorsten** [comment]
I will setup a minimal example when I am back from work!
Greetings

**Comment by DerThorsten** [comment]
Hi I have to correct my problem,
The problem are only private constructors.

**Comment by nbelakovski** [comment]
Here's a code sample and the corresponding compiler error. As DerThorsten noted, the issue is not with private constructors but in fact with private destructors. In addition to the base code sample, I also added a singleton accessor just to showcase a valid use case for having a private destructor.
```
#include <pybind11/pybind11.h>

class MyClass
{
public:
	MyClass * get_instance() {static MyClass a; return &a;}
	MyClass();
private:
	~MyClass();
	
};


PYBIND11_PLUGIN(example) {
	pybind11::module m("example", "pybind11 example plugin");
	
	pybind11::class_<MyClass>(m, "MyClass")
		.def(pybind11::init<>())
		.def_static("get_instance", &MyClass::get_instance, pybind11::return_value_policy::reference)
		;

	return m.ptr();
}
```

The compile line:
```g++ -o pybind11_scripting.os -c -std=c++11 -fPIC -I/Users/nbelakovski/pybind11/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 pybind11_scripting.cpp```

And the corresponding error:
```
In file included from pybind11_scripting.cpp:1:
In file included from /Users/nbelakovski/pybind11/include/pybind11/pybind11.h:32:
In file included from /Users/nbelakovski/pybind11/include/pybind11/attr.h:13:
In file included from /Users/nbelakovski/pybind11/include/pybind11/cast.h:13:
In file included from /Users/nbelakovski/pybind11/include/pybind11/pytypes.h:12:
In file included from /Users/nbelakovski/pybind11/include/pybind11/common.h:74:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/forward_list:173:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2426:20: error: calling a private destructor of class
      'MyClass'
            delete __ptr;
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2625:13: note: in instantiation of member function
      'std::__1::default_delete<MyClass>::operator()' requested here
            __ptr_.second()(__tmp);
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2593:46: note: in instantiation of member function
      'std::__1::unique_ptr<MyClass, std::__1::default_delete<MyClass> >::reset' requested here
    _LIBCPP_INLINE_VISIBILITY ~unique_ptr() {reset();}
                                             ^
/Users/nbelakovski/pybind11/include/pybind11/pybind11.h:1001:31: note: in instantiation of member function 'std::__1::unique_ptr<MyClass,
      std::__1::default_delete<MyClass> >::~unique_ptr' requested here
                inst->holder.~holder_type();
                              ^
/Users/nbelakovski/pybind11/include/pybind11/pybind11.h:821:26: note: in instantiation of member function 'pybind11::class_<MyClass, std::__1::unique_ptr<MyClass,
      std::__1::default_delete<MyClass> >, MyClass>::dealloc' requested here
        record.dealloc = dealloc;
                         ^
pybind11_scripting.cpp:16:2: note: in instantiation of function template specialization 'pybind11::class_<MyClass, std::__1::unique_ptr<MyClass,
      std::__1::default_delete<MyClass> >, MyClass>::class_<>' requested here
        pybind11::class_<MyClass>(m, "MyClass")
        ^
pybind11_scripting.cpp:9:2: note: declared private here
        ~MyClass();
        ^
1 error generated.
```

So, there's an issue with private destructors. Boost.python gets around this issue with the no_init option when exposing the class. Could PyBind11 implement something similar?

**Comment by nbelakovski** [comment]
I should add, omitting the line to expose the constructor gives the same error. After that, making the constructor private also exposes the same error.

**Comment by nbelakovski** [comment]
I've found a workaround that seems reasonable, I'm not sure how I might work a solution like no_init into the pybind11 framework though. The issue boils down to the fact that the holder_type for the class is defaulted to unique_ptr, which uses default_delete on the class to create a destructor object. Fortunately, unique_ptr can be overridden with a specific destructor object, so I made a template class and invoked it in my code as follows:

```
template < typename T>
struct BlankDeleter
{
	void operator()(T * inst) const {}
};

PYBIND11_PLUGIN(example) {
    pybind11::module m("example", "pybind11 example plugin");
    pybind11::class_<MyClass, std::unique_ptr<MyClass, BlankDeleter<MyClass>>>(m, "MyClass");
    return m.ptr();
}
```

And now I can set both the constructor and the destructor of the class to be private, and not expose the constructor, and I can have my singleton managed by C++ and accessed in Python.

**Comment by nbelakovski** [comment]
I messed with this unique_ptr stuff a bit more and came up with a fix for PyBind11. In the template specification for `class_`, we can change `typename holder_type = std::unique_ptr<type>` to the rather long winded but effective
```typename holder_type = std::unique_ptr<type, std::conditional<std::is_destructible<type>::value, std::default_delete<type>, BlankDeleter<type>>::type>```

This would also mean that the BlankDeleter struct I mentioned in my previous post would need to be included. This solves the compile issue for classes with private destructors, or deleted destructors, and in the end I think it means that there's no need to re-implement no_init like boost python does, since, as @wjakob pointed out at the beginning of the thread, you can just not expose the constructor.

If others are OK with this code change, could I submit a PR? I'm new to contributing to github, so a little guidance would be appreciated 😃

**Comment by wjakob** [comment]
Hi @nbelakovski,

I don't think it's a good idea to add BlankDeleter directly to pybind11. The case that a destructor is private is rather special and this workaround is not foolproof. The user might use the constructor and not realize that pybind11 will never call the destructor, which would lead to memory leaks. The snippet you posted is nice because the intent is clear: "Please don't call the constructor. Yes, I know what I am doing" :). 

So instead, I would suggest to create a PR which adds your snippet from above to the documentation. This could be in a new section in "advanced.rst" titled "Classes with non-public destructors".

Best,
Wenzel

**Comment by nbelakovski** [comment]
Thanks for the feedback, I agree that implicitly blanking out the destructor is not very nice. I can make the changes to the documentation. Do you think it also makes sense to add the BlankDeleter to pybind11?

**Comment by dalboris** [comment]
Hi all, I am facing a related issue but in the case of using `shared_ptr` instead of `unique_ptr`. Here is a minimal example:

```
#include <pybind11/pybind11.h>

class Foo : public std::enable_shared_from_this<Foo> {
    Foo() = default;
    ~Foo() = default;

public:
    static std::shared_ptr<Foo> create() {
        struct A : std::allocator<Foo> {
            void construct(void* p) { ::new(p) Foo(); }
            void destroy(Foo* p) { p->~Foo(); }
        };
        return std::allocate_shared<Foo>(A());
    }
};

PYBIND11_MODULE(foo, m) {
    pybind11::class_<Foo, std::shared_ptr<Foo>>(m, "Foo")
        .def(pybind11::init(&Foo::create));
}
```
The intent is to enforce instances of `Foo` to be managed by `shared_ptr` (hence the private constructor/destructor + factory method), making it always safe to call `shared_from_this()`. The use of `std::allocate_shared` is only [one of the possible methods](https://stackoverflow.com/a/11344174/1951907) to give `shared_ptr` access to the otherwise inaccessible constructor/destructor, but I believe all other methods involving a protected/private destructor would also fail when wrapped with pybind11 with the same errors.

The above minimal example fails to compile with the following errors:
```
In file included from /usr/include/c++/7/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/7/memory:81,
                 from pybind11/include/pybind11/detail/common.h:145,
                 from pybind11/include/pybind11/pytypes.h:12,
                 from pybind11/include/pybind11/cast.h:13,
                 from pybind11/include/pybind11/attr.h:13,
                 from pybind11/include/pybind11/pybind11.h:43,
                 from foo.cpp:1:
/usr/include/c++/7/bits/shared_ptr_base.h: In instantiation of ‘std::__shared_count<_Lp>::__shared_count(_Ptr) [with _Ptr = Foo*; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2]’:
/usr/include/c++/7/bits/shared_ptr_base.h:595:22:   required from ‘std::__shared_count<_Lp>::__shared_count(_Ptr, std::false_type) [with _Ptr = Foo*; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2; std::false_type = std::integral_constant<bool, false>]’
/usr/include/c++/7/bits/shared_ptr_base.h:1079:64:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Yp*) [with _Yp = Foo; <template-parameter-2-2> = void; _Tp = Foo; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2]’
/usr/include/c++/7/bits/shared_ptr.h:129:46:   required from ‘std::shared_ptr<_Tp>::shared_ptr(_Yp*) [with _Yp = Foo; <template-parameter-2-2> = void; _Tp = Foo]’
pybind11/include/pybind11/pybind11.h:1280:13:   required from ‘static void pybind11::class_<type_, options>::init_holder(pybind11::detail::instance*, pybind11::detail::value_and_holder&, const holder_type*, const std::enable_shared_from_this<T>*) [with T = Foo; type_ = Foo; options = {std::shared_ptr<Foo>}; pybind11::class_<type_, options>::holder_type = std::shared_ptr<Foo>]’
pybind11/include/pybind11/pybind11.h:1317:20:   required from ‘static void pybind11::class_<type_, options>::init_instance(pybind11::detail::instance*, const void*) [with type_ = Foo; options = {std::shared_ptr<Foo>}]’
pybind11/include/pybind11/pybind11.h:1053:30:   required from ‘pybind11::class_<type_, options>::class_(pybind11::handle, const char*, const Extra& ...) [with Extra = {}; type_ = Foo; options = {std::shared_ptr<Foo>}]’
foo.cpp:18:57:   required from here
/usr/include/c++/7/bits/shared_ptr_base.h:588:8: error: ‘Foo::~Foo()’ is private within this context
        delete __p;
        ^~~~~~
foo.cpp:5:5: note: declared private here
     ~Foo() = default;
     ^
In file included from /usr/include/c++/7/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/7/memory:81,
                 from pybind11/include/pybind11/detail/common.h:145,
                 from pybind11/include/pybind11/pytypes.h:12,
                 from pybind11/include/pybind11/cast.h:13,
                 from pybind11/include/pybind11/attr.h:13,
                 from pybind11/include/pybind11/pybind11.h:43,
                 from foo.cpp:1:
/usr/include/c++/7/bits/shared_ptr_base.h: In instantiation of ‘void std::_Sp_counted_ptr<_Ptr, _Lp>::_M_dispose() [with _Ptr = Foo*; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2]’:
foo.cpp:20:1:   required from here
/usr/include/c++/7/bits/shared_ptr_base.h:376:9: error: ‘Foo::~Foo()’ is private within this context
       { delete _M_ptr; }
         ^~~~~~
foo.cpp:5:5: note: declared private here
     ~Foo() = default;
     ^
```
The issue is fixed by either making `~Foo` public, or by removing [these four lines](https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L1279) in the definition of class_::init_holder():

```
    /// Initialize holder object, variant 1: object derives from enable_shared_from_this
    template <typename T>
    static void init_holder(detail::instance *inst, detail::value_and_holder &v_h,
            const holder_type * /* unused */, const std::enable_shared_from_this<T> * /* dummy */) {
        try {
            auto sh = std::dynamic_pointer_cast<typename holder_type::element_type>(
                    v_h.value_ptr<type>()->shared_from_this());
            if (sh) {
                new (std::addressof(v_h.holder<holder_type>())) holder_type(std::move(sh));
                v_h.set_holder_constructed();
            }
        } catch (const std::bad_weak_ptr &) {}

        // XXX:Boris Commented to fix compile errors
        // if (!v_h.holder_constructed() && inst->owned) {
        //    new (std::addressof(v_h.holder<holder_type>())) holder_type(v_h.value_ptr<type>());
        //    v_h.set_holder_constructed();
        //}
    }
```

Although I am highly unfamiliar with all the template magic of pybind11, my understanding is that it is safe to comment these lines in my case since `Foo::shared_from_this()` should never fail and `sh` should never be null. But obviously, it is not an acceptable "fix" for pybind11 in the general case since I suppose it would break other use cases relying on these lines of code.

Any thoughts? Better fix?

For the time being, I'm using the following instead of commenting the lines, so I can at least be aware of potential issues during development:
```
        if (!v_h.holder_constructed() && inst->owned) {
            assert(false && "Unexpected nullptr or std::bad_weak_ptr exception after calling shared_from_this()");
            //new (std::addressof(v_h.holder<holder_type>())) holder_type(v_h.value_ptr<type>());
            //v_h.set_holder_constructed();
        }
```
