### ISSUE TITLE
Can I use pybind11 from within a C++ application to create python plugins?

### ISSUE THREAD

**Issue by gauteh** [wjakob/pybind11#30]
Hi,

I am looking for a way to create python plugins for my c++ applications. That is, load a user-defined .py file and run a python function in it with arguments from my running C++ application.

Can I do that with pybind11?

**Comment by wjakob** [comment]
In principle yes: you can use ``pybind::function::call(...)`` to call Python functions though you'll likely have to do a few Python API calls to import new source code. (Pull requests welcomed if you want to create bindings for that)

**Comment by gauteh** [comment]
ok, thanks. in this case, would I have to create a common python
extension which knows about the C++ types or can I just register them
(if needed) in the calling C++ code and pass them to the function?

**Comment by wjakob** [comment]
Anything goes -- this is really mostly a design decision.

**Comment by gauteh** [comment]
okidoki. thanks, I am looking forward to testing out pybind.

Wenzel Jakob writes on December 14, 2015 12:50:

**Comment by skebanga** [comment]
@wjakob where can I find information about this please? 

That is, AFAICS, the vast bulk of the documentation is focused on exporting C++ code to python, not on running python code from within c++.

I can't find anything about `function::call` in the [reference](http://pybind11.readthedocs.io/en/latest/reference.html) (there is `handle::call` thought - not sure if this is what I should be using?)

Are there any examples showing `python -> c++`, rather than `c++ -> python`?

TIA!
