### ISSUE TITLE
From Boost.Python to PYBIND11

### ISSUE THREAD

**Issue by sgwoodjr** [wjakob/pybind11#5]
Hi,
First off, great job on the library. It looks very promising. 

Now to my question. I have a set of functions where each one returns a custom container class called _vec_. Below is an example wrapper using boost.python with num_util by Phil Austin. Basically num_util takes an iterator and returns a numpy array. 

How would I achieve the same results using pybind11?

```c++
namespace nbpl = num_util;
namespace bp = boost::python;

bpn::array mybartlett(int L)
{
    // This is a call to my custom function that returns a custom vector
    vec w = bartlett(L);

    // This copies the data in w into the numpy array out
    bpn::array out = nbpl::makeNum(w.begin(), w.size());

    return out;
}
```

**Comment by wjakob** [comment]
The simplest way would be to just use the builtin STL support (see the docs + examples) by converting your custom type to a std::vector. Otherwise, you could replicate the functionality of nbpl::makeNum by writing code which converts your type to a pybind::list (analogous to the boost::python::list wrapper). This should not be hard with the documentation + example materials.

**Comment by wjakob** [comment]
(feel free to reopen if this does not address your question)
