### ISSUE TITLE
Python 2.7 and earlier version of Visual Studio (2008)

### ISSUE THREAD

**Issue by SylvainCorlay** [wjakob/pybind11#85]
Since Python extensions typically have to be built with the same version of Visual Studio used to compile Python itself, I was wondering if one could use pybind11 with Python 2.7 on windows, since pybind11 is not compatible with Visual 2008.

It is my understanding that more recent versions of MSVC can be used if our C++ code does not access any C runtime object created by the Python interpreter (cf first reply in [stack overflow post](http://stackoverflow.com/questions/24708248/can-i-develop-c-extensions-for-python-2-7-through-3-1-on-windows-without-insta))

Another question is: what are the C++11 features missing in vs2013 for pybind11 to work well with it? Is it possible with minor changes to bridge the gap?

**Comment by SylvainCorlay** [comment]
cc @jmabille

**Comment by wjakob** [comment]
It's no problem to use pybind11 with a Python version that was built with an older version of MSVC. For instance, pybind11 will never free() a memory region that was malloc()ed by Python, and vice versa. The same holds true for other problematic C library functions.

It's highly unlikely that you will be able to get pybind11 to run on visual studio 2013 (I have tried and failed). Technically, the this version actually supports most necessary features -- the problem is that there are very severe bugs in the implementation of essential new features (tuples, variadic templates) which cause the compiler to segfault :(

**Comment by SylvainCorlay** [comment]
Thanks for your response @wjakob . This is an awesome project you have got here. Thanks!
